### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by meeng251** [leftthomas/SRGAN#75]
Hi @leftthomas @developer0hye @anant15 @mukulkhanna , this is the first time I've run this code and have the problem below:

# generator parameters: 734219
# discriminator parameters: 5215425

Traceback (most recent call last):
  File "train.py", line 87, in <module>
    g_loss = generator_criterion(fake_out, fake_img, real_img)
  File "V:\Anaconda\envs\SRGANs\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\SRProject\Leftthosmas-SRGAN\loss.py", line 21, in forward
    perception_loss = self.mse_loss(self.loss_network(out_images), self.loss_network(target_images))
  File "V:\Anaconda\envs\SRGANs\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "V:\Anaconda\envs\SRGANs\lib\site-packages\torch\nn\modules\container.py", line 117, in forward
    input = module(input)
  File "V:\Anaconda\envs\SRGANs\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "V:\Anaconda\envs\SRGANs\lib\site-packages\torch\nn\modules\conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "V:\Anaconda\envs\SRGANs\lib\site-packages\torch\nn\modules\conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)

RuntimeError: CUDA out of memory. Tried to allocate 122.00 MiB (GPU 0; 4.00 GiB total capacity; 2.76 GiB already allocated; 84.47 MiB free; 2.81 GiB reserved in total by PyTorch)
----------------------------------------------------
Could you help me this problem, my device infor: 
- Pytorch 1.6.0 with CUDA 10.1
- Torchvision 0.7.0
- I5-8300H + GTX 1050Ti 4GB 
- Dataset: VOC2012 for train and val

**Comment by developer0hye** [comment]
@meeng251 
Train model with lower batch size!

**Comment by meeng251** [comment]
@developer0hye where can I modify code which contains batch_size ? (which file and which line) 
is this batch_size = x.size(0) in model.py 
or in train.py 
    train_loader = DataLoader(dataset=train_set, num_workers=4, batch_size=64, shuffle=True)
    val_loader = DataLoader(dataset=val_set, num_workers=4, batch_size=1, shuffle=False)

**Comment by developer0hye** [comment]
@meeng251 
in train.py

Try to change batch size 64 to 32, 16, 8, 4, 2, and 1.

**Comment by meeng251** [comment]
So can you guide me, i'm a newbie. Thank you :( 
@leftthomas  @developer0hye

**Comment by meeng251** [comment]
@developer0hye 
Oh, that's mean I try each one batch size right (Sorry I'm a newbie) ? 

Are there any more places to modify batch size?

**Comment by developer0hye** [comment]
@meeng251 
Yes, I mean that.

Try! Try!

**Comment by JLxiaocaiji** [comment]
Now,you need a new friend---------3090

**Comment by meeng251** [comment]
@leftthomas  @developer0hye 
I changed batch_size from 64 to 32 in train.py:
from
- train_loader = DataLoader(dataset=train_set, num_workers=4, batch_size=64, shuffle=True)

to
- train_loader = DataLoader(dataset=train_set, num_workers=4, batch_size=32, shuffle=True)

And got an error like this: 
Traceback (most recent call last):
  File "train.py", line 88, in <module>
    g_loss.backward()
  File "V:\Anaconda\envs\SRGANs\lib\site-packages\torch\tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "V:\Anaconda\envs\SRGANs\lib\site-packages\torch\autograd\__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 1024, 1, 1]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

I don't know why, could you have me, thank you 👍

**Comment by JLxiaocaiji** [comment]
first:torch.autograd.set_detect_anomaly(True)
then:change a += 1 to a = a+1
finally: try to google

**Comment by emanuelevivoli** [comment]
Hi, that problem is resolved in #57, you need to use version 10 of cuda and version 1.0 of pytorch.
If you are using Anaconda or Miniconda, you should take a look to [this](https://medium.com/@_willfalcon/how-to-install-pytorch-1-0-with-cuda-10-0-169569c5b82d) and [this](https://pytorch.org/get-started/previous-versions/#linux-and-windows-12) to create your env with the right configuration.
